### PR TITLE
Fix sending logs multiple times in PureeOutput#flushSync()

### LINKED ISSUE #48: Puree.flush() is broken: it send logs multiple times

### PR DESCRIPTION
**Pull request by nein37**
Fix #48

### CODE REVIEW

File: puree/src/main/java/com/cookpad/puree/outputs/PureeBufferedOutput.java [hunk 1]
```diff
@@ -64,12 +61,13 @@ public void run() {
...
 
     public void flushSync() {
-        if (!lock.compareAndSet(false, true)) {
+        if (!storage.lock()) {
             return;
         }
         final Records records = getRecordsFromStorage();
 
         if (records.isEmpty()) {
+            storage.unlock();
```
Comment (gfx) [inline puree/src/main/java/com/cookpad/puree/outputs/PureeBufferedOutput.java]: :white_check_mark:  It's the problem. Nice.

**Comment by gfx** [comment]
LGTM
